export const ADD_INGRIDIENTS = 'ADD_INGRIDIENTS';
export const REMOVE_INGRIDIENTS = 'REMOVE_INGRIDIENTS';
export const SET_INGRIDIENTS = 'SET_INGRIDIENTS';
export const FETCH_INGRIDIENTS_FAILED = 'FETCH_INGRIDIENTS_FAILED';